### ISSUE TITLE
Homepage (dashboard)

### ISSUE THREAD

**Issue by achlin** [LightningAir/wacky-webapp#37]
Our homepage contains a dashboard of sorts.

Ensure the displayed data should now be provided or calculated from our database. 
I believe this is already the case from [release v1.0](https://github.com/LightningAir/wacky-webapp/tree/v1.0). Comment and close the ticket if this is already the case.

This page is accessible to any user role (a.k.a. "Guest").

**Comment by kculala** [comment]
done in [release v1.0.](https://github.com/LightningAir/wacky-webapp/tree/v1.0)
